algoritmo "semnome"
// Função :
// Autor :
// Data : 11/11/2020
// Seção de Declarações 
var
c1, c2, c3, c4, c5, c6, c7, c8 ,c9: Inteiro
inicio
c1 <- 0
Escreva (c1)
c2 <- c1 + 1
Escreva (c2)
c3 <- c2 + c1
Escreva (c3)
c4 <- c3 + c2
Escreva (c4)
c5 <- c4 + c3
Escreva (c5)
c6 <- c5 + c4
Escreva (c6)
c7 <- c6 + c5
Escreva (c7)
c8 <- c7 + c6
Escreva (c8)
c9 <- c8 + c7
Escreva (c9)
cont <- cont + 1









fimalgoritmo
