algoritmo "semnome"
// Função :
// Autor :
// Data : 03/11/2020
// Seção de Declarações 
var
cont, n1, n2, salto: Inteiro
inicio
      Escreval ("Digite um número")
      Leia (n1)
      Escreval ("Quer contar até quanto")
      Leia (n2)
      Escreval ("Escreva o valor do salto")
      Leia (salto)
      cont <- n1
      Enquanto (cont >= n1) e (cont <= n2)  faca
      Escreval (cont)
      cont <- cont + salto
      Fimenquanto

      
fimalgoritmo
